name: noise2inverse
channels:
- pytorch
- defaults
- conda-forge
- astra-toolbox/label/dev
- aahendriksen
dependencies:
- python=3.6
- pip
- ipython
- ipykernel
# MS-D, CUDA, pytorch
- cudatoolkit=10.0
- msd_pytorch=0.7.2
# plotting and utilities
- scikit-image
- matplotlib
- seaborn
- tifffile
- tqdm
# Tomography
- foam_ct_phantom
- tomopy
- astra-toolbox=1.9.0.dev11
- libastra=1.9.0.dev11
- pip:
  - git+https://github.com/ahendriksen/tomosipo.git@develop
  - bm3d
